#!/bin/bash
# First-Boot Setup Wizard for Shatter CNC Platform
# This script runs on first boot to configure WiFi and generate credentials

set -e

SETUP_COMPLETE_FILE="/opt/shatter/.setup-complete"
ENV_FILE="/opt/shatter/.env"

# Check if setup has already been completed
if [ -f "$SETUP_COMPLETE_FILE" ]; then
    echo "Setup already completed. Skipping wizard."
    exit 0
fi

echo ""
echo "=========================================="
echo "  Shatter CNC Platform - Setup Wizard"
echo "=========================================="
echo ""

# Function to generate random password
generate_password() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

# Function to generate secret key
generate_secret_key() {
    openssl rand -hex 32
}

# WiFi Configuration
echo "=== WiFi Configuration ==="
echo ""
echo "Do you want to configure WiFi? (y/n)"
read -r configure_wifi

if [ "$configure_wifi" = "y" ] || [ "$configure_wifi" = "Y" ]; then
    echo ""
    echo "Available WiFi networks:"
    iwlist wlan0 scan 2>/dev/null | grep ESSID | sed 's/.*ESSID:"\(.*\)".*/\1/' | sort -u || echo "Unable to scan (may need to run as root)"
    echo ""
    echo "Enter WiFi SSID:"
    read -r wifi_ssid
    echo "Enter WiFi password:"
    read -rs wifi_password
    echo ""
    
    # Configure WiFi
    if [ -n "$wifi_ssid" ] && [ -n "$wifi_password" ]; then
        cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
    ssid="$wifi_ssid"
    psk="$wifi_password"
}
EOF
        echo "WiFi configuration saved. Restarting network..."
        wpa_cli -i wlan0 reconfigure 2>/dev/null || systemctl restart networking || true
        echo "Waiting for network connection..."
        sleep 10
    fi
fi

# Generate secure credentials
echo ""
echo "=== Generating Secure Credentials ==="
POSTGRES_PASSWORD=$(generate_password)
REDIS_PASSWORD=$(generate_password)
SECRET_KEY=$(generate_secret_key)

echo ""
echo "Generated credentials:"
echo "  POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
echo "  REDIS_PASSWORD: $REDIS_PASSWORD"
echo "  SECRET_KEY: $SECRET_KEY"
echo ""
echo "IMPORTANT: Save these credentials in a secure location!"
echo ""
echo "Press Enter to continue..."
read -r

# Create .env file
echo ""
echo "=== Creating Configuration File ==="
cat > "$ENV_FILE" << EOF
# Shatter CNC Platform - Environment Variables
# Generated by setup wizard on $(date)

# Database Configuration
POSTGRES_DB=shatter
POSTGRES_USER=shatter_user
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Redis Configuration
REDIS_HOST=redis
REDIS_PASSWORD=$REDIS_PASSWORD

# Application Configuration
LOG_LEVEL=WARNING
DEFAULT_POLL_INTERVAL=5
SECRET_KEY=$SECRET_KEY

# Backend Port
BACKEND_PORT=8000

# GitHub Container Registry
GITHUB_OWNER=roblockwood
GITHUB_REPO=shatter-nc
IMAGE_TAG=latest
EOF

chmod 600 "$ENV_FILE"
chown pi:pi "$ENV_FILE"

echo "Configuration file created at $ENV_FILE"

# Update docker-compose.prod.yml to use .env file
cd /opt/shatter
if [ -f "docker-compose.prod.yml" ]; then
    # Ensure docker-compose uses the .env file
    echo "Docker Compose will use .env file for environment variables"
fi

# Start Docker Compose services
echo ""
echo "=== Starting Services ==="
echo "This may take a few minutes on first boot..."

# Ensure Docker is running
systemctl start docker || service docker start
sleep 5

# Start services
cd /opt/shatter
docker compose -f docker-compose.prod.yml up -d

# Wait for services to be healthy
echo "Waiting for services to start..."
sleep 30

# Check service status
echo ""
echo "=== Service Status ==="
docker compose -f docker-compose.prod.yml ps

# Mark setup as complete
touch "$SETUP_COMPLETE_FILE"
chown pi:pi "$SETUP_COMPLETE_FILE"

# Disable the setup service (don't run again)
systemctl disable shatter-setup.service

echo ""
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "Shatter CNC Platform is now running."
echo ""
echo "Access the web interface at:"
echo "  http://shatter.local"
echo "  http://$(hostname -I | awk '{print $1}')"
echo ""
echo "Your credentials have been saved to:"
echo "  $ENV_FILE"
echo ""
echo "To view service logs:"
echo "  sudo journalctl -u shatter.service -f"
echo ""
echo "To restart services:"
echo "  sudo systemctl restart shatter.service"
echo ""
