#!/bin/bash
# Manual Installation Script for Shatter CNC Platform
# This script installs Shatter on an existing Raspberry Pi system
# Usage: curl -fsSL https://raw.githubusercontent.com/roblockwood/shatter-nc/main/scripts/install-shatter.sh | bash

set -e

echo ""
echo "=========================================="
echo "  Shatter CNC Platform - Manual Install"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo "Error: Do not run this script as root. Run as a regular user with sudo privileges."
    exit 1
fi

# Check for sudo access
if ! sudo -n true 2>/dev/null; then
    echo "This script requires sudo privileges. Please enter your password when prompted."
fi

# Detect architecture
ARCH=$(uname -m)
if [ "$ARCH" != "aarch64" ] && [ "$ARCH" != "armv7l" ]; then
    echo "Warning: This script is designed for Raspberry Pi (ARM architecture)"
    echo "Detected architecture: $ARCH"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Installation directory
INSTALL_DIR="/opt/shatter"
REPO_URL="https://github.com/roblockwood/shatter-nc.git"

echo ""
echo "=== Checking Prerequisites ==="

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo "Docker not found. Installing Docker..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sudo sh /tmp/get-docker.sh
    rm /tmp/get-docker.sh
    sudo usermod -aG docker $USER
    echo "Docker installed. You may need to log out and back in for group changes to take effect."
    echo "Please log out and run this script again."
    exit 0
else
    echo "✓ Docker is installed"
    docker --version
fi

# Check for Docker Compose
if ! docker compose version &> /dev/null; then
    echo "Docker Compose not found. Installing Docker Compose V2..."
    sudo mkdir -p /usr/local/lib/docker/cli-plugins
    sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64 -o /usr/local/lib/docker/cli-plugins/docker-compose
    sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
    echo "✓ Docker Compose installed"
else
    echo "✓ Docker Compose is installed"
    docker compose version
fi

# Check for Git
if ! command -v git &> /dev/null; then
    echo "Git not found. Installing Git..."
    sudo apt-get update
    sudo apt-get install -y git
fi

echo ""
echo "=== Installing Shatter ==="

# Create installation directory
sudo mkdir -p "$INSTALL_DIR"
sudo chown $USER:$USER "$INSTALL_DIR"

# Clone repository or download files
if [ -d "$INSTALL_DIR/.git" ]; then
    echo "Repository already exists. Updating..."
    cd "$INSTALL_DIR"
    git pull
else
    echo "Cloning repository..."
    git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# Copy docker-compose.prod.yml
if [ ! -f "$INSTALL_DIR/docker-compose.prod.yml" ]; then
    cp docker-compose.prod.yml "$INSTALL_DIR/docker-compose.prod.yml"
fi

# Install Avahi if not installed
if ! command -v avahi-daemon &> /dev/null; then
    echo "Installing Avahi..."
    sudo apt-get update
    sudo apt-get install -y avahi-daemon avahi-utils
fi

# Configure Avahi
echo "Configuring Avahi..."
sudo mkdir -p /etc/avahi/services
sudo cp avahi/shatter.service /etc/avahi/services/shatter.service
sudo systemctl enable avahi-daemon
sudo systemctl restart avahi-daemon

# Run setup wizard
echo ""
echo "=== Running Setup Wizard ==="
if [ -f "$INSTALL_DIR/pi-image/files/setup-wizard.sh" ]; then
    cp "$INSTALL_DIR/pi-image/files/setup-wizard.sh" "$INSTALL_DIR/setup-wizard.sh"
    chmod +x "$INSTALL_DIR/setup-wizard.sh"
    "$INSTALL_DIR/setup-wizard.sh"
else
    echo "Setup wizard not found. Creating basic configuration..."
    
    # Generate credentials
    generate_password() {
        openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
    }
    
    generate_secret_key() {
        openssl rand -hex 32
    }
    
    POSTGRES_PASSWORD=$(generate_password)
    REDIS_PASSWORD=$(generate_password)
    SECRET_KEY=$(generate_secret_key)
    
    cat > "$INSTALL_DIR/.env" << EOF
# Shatter CNC Platform - Environment Variables
# Generated by install script on $(date)

POSTGRES_DB=shatter
POSTGRES_USER=shatter_user
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

REDIS_HOST=redis
REDIS_PASSWORD=$REDIS_PASSWORD

LOG_LEVEL=WARNING
DEFAULT_POLL_INTERVAL=5
SECRET_KEY=$SECRET_KEY

BACKEND_PORT=8000

GITHUB_OWNER=roblockwood
GITHUB_REPO=shatter-nc
IMAGE_TAG=latest
EOF
    
    chmod 600 "$INSTALL_DIR/.env"
    echo "Configuration file created at $INSTALL_DIR/.env"
    echo ""
    echo "Generated credentials:"
    echo "  POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
    echo "  REDIS_PASSWORD: $REDIS_PASSWORD"
    echo "  SECRET_KEY: $SECRET_KEY"
    echo ""
    echo "IMPORTANT: Save these credentials!"
    echo ""
    read -p "Press Enter to continue..."
fi

# Install systemd service
echo ""
echo "=== Installing Systemd Service ==="
if [ -f "$INSTALL_DIR/pi-image/files/shatter.service" ]; then
    sudo cp "$INSTALL_DIR/pi-image/files/shatter.service" /etc/systemd/system/shatter.service
    sudo systemctl daemon-reload
    sudo systemctl enable shatter.service
    echo "✓ Systemd service installed and enabled"
fi

# Pull Docker images
echo ""
echo "=== Pulling Docker Images ==="
cd "$INSTALL_DIR"
export $(cat .env | xargs)
docker compose -f docker-compose.prod.yml pull || echo "Warning: Some images may require authentication"

# Start services
echo ""
echo "=== Starting Services ==="
docker compose -f docker-compose.prod.yml up -d

# Wait for services
echo "Waiting for services to start..."
sleep 30

# Show status
echo ""
echo "=== Service Status ==="
docker compose -f docker-compose.prod.yml ps

echo ""
echo "=========================================="
echo "  Installation Complete!"
echo "=========================================="
echo ""
echo "Shatter CNC Platform is now running."
echo ""
echo "Access the web interface at:"
echo "  http://shatter.local"
echo "  http://$(hostname -I | awk '{print $1}')"
echo ""
echo "Configuration file: $INSTALL_DIR/.env"
echo ""
echo "Useful commands:"
echo "  View logs:        sudo journalctl -u shatter.service -f"
echo "  Restart services: sudo systemctl restart shatter.service"
echo "  Stop services:    sudo systemctl stop shatter.service"
echo "  View containers:  docker compose -f $INSTALL_DIR/docker-compose.prod.yml ps"
echo ""
